apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patch-gateway-resources.yaml
  - path: patch-operator-resources.yaml

images:
  - name: ghcr.io/latchkey/latchkey-gateway
    newName: latchkey-gateway
    newTag: dev
  - name: ghcr.io/latchkey/latchkey-operator
    newName: latchkey-operator
    newTag: dev
  - name: ghcr.io/latchkey/latchkey-tool-server
    newName: latchkey-tool-server
    newTag: dev
  - name: ghcr.io/latchkey/latchkey-upstream-stub
    newName: latchkey-upstream-stub
    newTag: dev
