apiVersion: v1
kind: Service
metadata:
  name: latchkey-tool-server
spec:
  selector:
    app.kubernetes.io/name: latchkey-tool-server
  ports:
    - name: http
      port: 8081
      targetPort: 8081
