apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: latchkey-gateway
rules:
  - apiGroups:
      - latchkey.dev
    resources:
      - latchkeyservers
      - latchkeytools
      - latchkeyprincipals
      - latchkeypolicies
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: latchkey-gateway
subjects:
  - kind: ServiceAccount
    name: latchkey-gateway
    namespace: latchkey-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: latchkey-gateway
